### ISSUE TITLE
.rubocop.yml

### ISSUE THREAD

**Issue by cpkPitt** [laboon/CS1632_Fall2018#11]
The .rubocop.yml file that you gave us, on my machine (Ubuntu) running rubocop version 0.59.2 shows a warning indicating that the last line "Style/EndOfLine Enabled: false" should be "Layout/EndOfLine Enabled: false" then, when I make the change, this warning goes away

jarvis@laptop:~/Desktop/School/CS 1632/D2/D2-master$ rubocop map.rb
.rubocop.yml: Style/EndOfLine has the wrong namespace - should be Layout
Inspecting 1 file

jarvis@laptop:~/Desktop/School/CS 1632/D2/D2-master$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

jarvis@laptop:~/Desktop/School/CS 1632/D2/D2-master$ rubocop -v
0.59.2

**Comment by laboon** [comment]
Apparently my version of rubocop does not display the warning for  me and silently fixes it.  However, it works for both Style and Layout, so I will change it to Layout.

+1 EC
