### ISSUE TITLE
D2 - Running rubocop with our all_tests.rb file

### ISSUE THREAD

**Issue by minj131** [laboon/CS1632_Fall2018#12]
For the rubocop check, is there a way to have the all_tests.rb run rubocop on our files and run the tests at the same time? Or should we run rubocop seperately and provide the screenshots for the results?

I wasn't able to find any sample that had rubocop included with the test file.

**Comment by laboon** [comment]
```
ls -1 *.rb | grep -v _test | xargs rubocop
```

should work

Note that it is a "dash one" not a "dash ell"

**Comment by laboon** [comment]
Sorry I think I misunderstood.  That will run rubocop on all non-test files.

You should run rubocop separately than the tests.
