### ISSUE TITLE
Class Planned for Nov 21st

### ISSUE THREAD

**Issue by surbhipatel98** [laboon/CS1632_Fall2018#3]
On the current version of the syllabus there is a lesson planned for November 21st, however the university will be closed that day for Thanksgiving Break. 

-Surbhi Patel (sup47)

**Comment by laboon** [comment]
Good catch!  +1 extra credit

**Comment by laboon** [comment]
fixed on commit 214e3338714cb8ab0e65261db239bef0cdafcd30
