### ISSUE TITLE
Lecture 4 Smoke Exploratory Path Slide 32 Error

### ISSUE THREAD

**Issue by AJM249** [laboon/CS1632_Fall2018#7]
My name is Anthony Martrano.  In the laboonify method on the slide, there is a variable named "toReturn" that is never declared and initialized in the method.  However, there is another variable called "initialVal" that is declared and initialized to be the sum of x and y, but it is not used again.  Did you meant to write "int combo = initialVal + normalized;" instead of "int combo = toReturn + normalized;"?

**Comment by laboon** [comment]
Yes, this got a bit mixed up when transcribing.  +0.5 EC
