### ISSUE TITLE
Lecture 5, minitest assert_true

### ISSUE THREAD

**Issue by atdifurio** [laboon/CS1632_Fall2018#8]
My name is Andrew DiFurio. In Lecture 5: Intro to Unit Testing states that assert_true is a minitest assertion. However, I don't see this method in the Ruby docs. [Here](http://ruby-doc.org/stdlib-2.0.0/libdoc/minitest/rdoc/MiniTest/Assertions.html) is a link to the ruby-doc that shows all minitest methods. 

I tried to use minitest and this test passed.
```
def test_assert_true_exists
    assert_raises (NoMethodError){assert_true true} 
end
```

**Comment by laboon** [comment]
Sorry this should just be "assert".  I will fix and give you +0.5 extra credit.

**Comment by laboon** [comment]
Actually this seems like a bigger deal since it's incorrect syntax. +1 EC

**Comment by laboon** [comment]
Plus you added a nice failing test.  👍 🏆
